#!/usr/bin/env bash

# Install homebrew
which -s brew
if [[ $? != 0 ]] ; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update homebrew and install packages
brew update
brew bundle --file=~/.dotfiles/config/Brewfile

# Install powerline fonts
git clone https://github.com/powerline/fonts.git --depth=1
cd fonts
./install.sh
cd ..
rm -rf fonts

# Run dotbot
~/.dotfiles/install

# Setup ZSH
~/.dotfiles/setup-zsh
