#!/usr/bin/env bash

# Install homebrew
which -s brew
if [[ $? != 0 ]] ; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update homebrew and install packages
brew update
brew bundle

# Setup ZSH
~/.dotfiles/setup-zsh

# Run dotbot
~/.dotfiles/install